name: Test and Release

# Run this job on all pushes to main and for pull requests
on:
  push:
    branches:
      # This avoids having duplicate builds in non-forked PRs
      - "main"
  pull_request: {}

# Cancel previous PR/branch runs when a new commit is pushed
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ===================
  # Catches style errors
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # This should be LTS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --immutable

    - name: Compile TypeScript code
      run: yarn build

    - name: Run linter
      run: yarn run lint

  # ===================
  # Runs unit tests
  unit-tests:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # This should be LTS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --immutable

    # Compilation is necessary, or the tests won't run
    - name: Compile TypeScript code
      run: yarn run build

    - name: Run component tests
      run: yarn run test:ci
